version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/hosts:/etc/nginx/conf.d
      - ./:/var/app
      - ./.docker/nginx/logs:/var/log/nginx
    links:
      - php
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - db_data:/var/lib/mysql
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/app
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

volumes:
  db_data: